[2023-10-03T07:43:52.104+0000] {processor.py:157} INFO - Started process (PID=30) to work on /opt/airflow/dags/producer.py
[2023-10-03T07:43:52.104+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/producer.py for tasks to queue
[2023-10-03T07:43:52.106+0000] {logging_mixin.py:151} INFO - [2023-10-03T07:43:52.106+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/producer.py
[2023-10-03T07:43:52.113+0000] {logging_mixin.py:151} INFO - [2023-10-03T07:43:52.112+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/producer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/producer.py", line 9, in <module>
    start_date = datetime(2022, 1, 1),
NameError: name 'datetime' is not defined
[2023-10-03T07:43:52.114+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/producer.py
[2023-10-03T07:43:52.128+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/producer.py took 0.028 seconds
[2023-10-03T07:44:22.371+0000] {processor.py:157} INFO - Started process (PID=89) to work on /opt/airflow/dags/producer.py
[2023-10-03T07:44:22.373+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/producer.py for tasks to queue
[2023-10-03T07:44:22.377+0000] {logging_mixin.py:151} INFO - [2023-10-03T07:44:22.376+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/producer.py
[2023-10-03T07:44:22.386+0000] {logging_mixin.py:151} INFO - [2023-10-03T07:44:22.385+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/producer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/producer.py", line 9, in <module>
    start_date = datetime(2022, 1, 1),
NameError: name 'datetime' is not defined
[2023-10-03T07:44:22.387+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/producer.py
[2023-10-03T07:44:22.426+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/producer.py took 0.060 seconds
[2023-10-03T07:44:52.936+0000] {processor.py:157} INFO - Started process (PID=148) to work on /opt/airflow/dags/producer.py
[2023-10-03T07:44:52.937+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/producer.py for tasks to queue
[2023-10-03T07:44:52.939+0000] {logging_mixin.py:151} INFO - [2023-10-03T07:44:52.938+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/producer.py
[2023-10-03T07:44:52.950+0000] {logging_mixin.py:151} INFO - [2023-10-03T07:44:52.948+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/producer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/producer.py", line 9, in <module>
    start_date = datetime(2022, 1, 1),
NameError: name 'datetime' is not defined
[2023-10-03T07:44:52.951+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/producer.py
[2023-10-03T07:44:52.981+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/producer.py took 0.049 seconds
[2023-10-03T07:45:23.238+0000] {processor.py:157} INFO - Started process (PID=207) to work on /opt/airflow/dags/producer.py
[2023-10-03T07:45:23.241+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/producer.py for tasks to queue
[2023-10-03T07:45:23.269+0000] {logging_mixin.py:151} INFO - [2023-10-03T07:45:23.268+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/producer.py
[2023-10-03T07:45:23.329+0000] {logging_mixin.py:151} INFO - [2023-10-03T07:45:23.321+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/producer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/producer.py", line 9, in <module>
    start_date = datetime(2022, 1, 1),
NameError: name 'datetime' is not defined
[2023-10-03T07:45:23.331+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/producer.py
[2023-10-03T07:45:23.359+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/producer.py took 0.137 seconds
[2023-10-03T07:45:53.890+0000] {processor.py:157} INFO - Started process (PID=266) to work on /opt/airflow/dags/producer.py
[2023-10-03T07:45:53.891+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/producer.py for tasks to queue
[2023-10-03T07:45:53.894+0000] {logging_mixin.py:151} INFO - [2023-10-03T07:45:53.894+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/producer.py
[2023-10-03T07:45:53.901+0000] {logging_mixin.py:151} INFO - [2023-10-03T07:45:53.900+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/producer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/producer.py", line 9, in <module>
    start_date = datetime(2022, 1, 1),
NameError: name 'datetime' is not defined
[2023-10-03T07:45:53.901+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/producer.py
[2023-10-03T07:45:53.925+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/producer.py took 0.038 seconds
